### PR TITLE
Profile drawer

### PR DESCRIPTION
**Pull request by SuspenseFallback**
Added profile drawer.

### CODE REVIEW

**Comment by dadiorchen** [comment]
image

Is this the same as yours on your computer?

I think the UI is not so accurate, you know, as long as your implemetation pixel-accurate with the design, you will get a beautiful app:
1. The font size is big
2. Addjust the spacing for padding/margin
3. You can find my example of using custom icon with svg file, you are using MUI icons.

**Comment by dadiorchen** [comment]
@SuspenseFallback thank you for you work on this!

**Comment by SuspenseFallback** [comment]
Oh yeah, the paddings look fine on my computer, I'll try and change that. Also, I think the icons changed during merge, the files are still in the images folder, I'll add them back

**Comment by SuspenseFallback** [comment]
Screenshot 2023-08-07 at 10 15 51 AM

**Comment by dadiorchen** [comment]
@SuspenseFallback nice! can you do two one thing to make this PR ready:
1. Extract the draw to a dedicated component and put it into the folder `components`
2. Fix the conflict

**Comment by dadiorchen** [comment]
@SuspenseFallback great job, thank you!

**Pull request merged**
